@startuml FolderStructure
left to right direction
'top to bottom direction


skinparam defaultFontName Segoe UI
skinparam defaultFontSize 25
scale 1800*1800

<style>
    node {
        Fontcolor #000000
        LineThickness 1
        LineColor black
    }
    folder {
        Fontcolor  #000000
        'BackGroundColor #004073
        LineThickness 1
        LineColor black
    }
    package {
        BackGroundColor #12bdb9
        LineThickness 1
        LineColor black
    }

    file {
        BackGroundColor #d3d6de
        LineThickness 1
        LineColor black
    }

    component{
        BackGroundColor #d3d6de
        LineThickness 1
        LineColor black
    }
</style>

node "Data plotting" as "Storage"{
    folder "Graph_Functions" {
        [Scripts for Plot controlling and image generation]
        ' file "about_us.mlp"
        ' file "NR5G.mlap"
    }
    folder "Outputs" {
        [Data Base for simulation results]
        '  file "about_uspp"
        ' file "NR5G.mp"
    }
}
together {
node "Auxiliar ANNs Folders" as "Aux_folder"{
    folder "Generation" {
        [Generation scripts for ANNs ]
    }
    folder "Models" {
        [Neuronal Models in .mat format]
        ' file "bouus.mlapp"
        ' file "R5G.mlapp"
    }
}

node "Complementary modules " as "Complements"{
    folder "Functions" {
        [Main functions for 5G communications system]
        ' file "bout_us.mlapp"
        'file "R5G.mlapp"
    }
    folder "Estimation" {
        [Functions for channel estimacion using ANNs]
        'file "aboutus.mlapp"
        ' file "NR5.mlapp"
    }
}
}
node "Execution Elements" as "Execution"{
    folder "App" {
        [Main Files]
        
        ' file "NR5G.mlapp"
        '  file "Complet_Simulation.m"
        '  file "App_Waterfall_Estimation_Time.m"
        '  file "Init_Parameters.m"
    }
    file Script_Final.m
}

'Define Relations
/'
-left-> left
-right-> right
-up-> up
-down-> down
Functions --left-> Outputs

Graph_Functions -> Outputs

Aux_folder -> Complements

'/

Complements <--down-  Execution
Complements ---> Aux_folder
Execution ----> Storage
Complements ------> Outputs

@enduml
