@startuml
start

if (SNR Estático?) then (Sí)
  :Establecer SNR Estático;
else (No)
  :Establecer SNR Inicial;
  :Configurar Intervalos de SNR;
  :Establecer SNR Máximo;
endif

:Configurar Compensación de Fase;

if (Transmisión de Imagen?) then (Sí)
  :Definir Parámetros de Transmisión de Imagen;
  :Cargar Imagen;
elseif (Transmisión de Bits?) then (Sí)
  :Definir Parámetros de Transmisión de Bits;
  :Establecer Cantidad de Bits Deseados;
  :Establecer Número de Frames;
  :Definir Ruta de la Imagen;
  :Cargar Imagen;
else (No)
  :Transmisión de Imagen y Bits Desactivada;
endif

:Configurar Modelos de Estimación;

if (Estimación de Canal con CNN?) then (Sí, #008000)
  :Cargar Modelo de CNN;
  :Activar Estimación de Canal con CNN;
endif

if (Estimación de Canal con CNN_2?) then (Sí, #800080)
  :Cargar Modelo de CNN_2;
  :Activar Estimación de Canal con CNN_2;
endif

if (Estimación de Canal con Autoencoder?) then (Sí, #FF0000)
  :Cargar Modelo de Autoencoder;
  :Activar Estimación de Canal con Autoencoder;
endif

if (Estimación de Canal Práctica?) then (Sí, #0000FF)
  :Activar Estimación de Canal Práctica;
endif

if (Estimación de Canal con Red Denoising?) then (Sí, #008000)
  :Cargar Modelo de Red Denoising;
  :Activar Estimación de Canal con Red Denoising;
endif

if (Estimación de Canal con Red Denoising 2?) then (Sí, #800080)
  :Cargar Modelo de Red Denoising 2;
  :Activar Estimación de Canal con Red Denoising 2;
endif

:Iniciar Simulación de Transmisión;

while (Canal) is (en canales)
  :Configurar Canal;
  while (Modulación) is (en modulaciones)
    :Configurar Modulación;
    while (Velocidad) is (en velocidades)
      :Configurar Velocidad;
      :Configurar SNR;
      :Establecer Velocidad del Usuario;
      :Configurar Portadora, Modulación y Canal;
      :Inicialización de Parámetros;
      :Procesamiento de Slot;
      :Transmisor;
      :Receptor;
      :Estimación de Canal Lineal;
      :Estimación de Canal Perfecta;
      :Estimación de Canal con CNN;
      :Estimación de Canal con CNN_2;
      :Estimación de Canal con Autoencoder;
      :Estimación de Canal con Red Denoising;
      :Estimación de Canal con Red Denoising 2;
      :Estimación de Canal Práctica;
      :Métricas del Slot;
    endwhile
  endwhile
endwhile

:Guardar Parámetros;

stop
@enduml
