@startuml Variables_initialization

skinparam defaultFontName Segoe UI
skinparam defaultFontSize 25
scale 1800*1800
<style>
    node {
        Fontcolor #000000
        LineThickness 1
        LineColor black
    }
    folder {
        Fontcolor  #FFFFFF
        BackGroundColor #004073
        LineThickness 1
        LineColor black
    }
    package {
        BackGroundColor #12bdb9
        LineThickness 1
        LineColor black
    }

    file {
        BackGroundColor #d3d6de
        LineThickness 1
        LineColor black
    }

    component{
        BackGroundColor #d3d6de
        LineThickness 1
        LineColor black
    }
</style>
class Variables_initialization {
  -Parameters: struct
  +Est: struct
  +Variables_initialization(Parameters, snr: double)
}

class Parameters {
  -txbits: double[]
  -SNR_Lineal: double
  -block_posicion: double
  -step: double
  -End_pos: double
  -CNN_pdschEq_sin: double[]
}

Variables_initialization -- Parameters

@enduml
